#!/bin/bash
#
# This script is intended for @xironix's internal use in building and updating
# the FreeBSD Vagrant boxes.

# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.
# Source @davejamesmiller - https://gist.github.com/davejamesmiller/1965569
function ask {
  while true; do
    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question
    read -p "$1 [$prompt] " REPLY

    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

echo -e "\033[1;32mUpdating config files...\n\033[0m"
#scp -r ../config/* freebsd:/

echo -e "\033[1;32mRestoring ownership of vagrant home to vagrant...\n\033[0m"
#ssh freebsd "chown -R vagrant:vagrant /usr/home/vagrant"

echo -e "\033[1;32mUpdating ports tree...\n\033[0m"
#ssh freebsd "svn update /usr/ports"

echo -e "\033[1;32mUpdating installed ports...\n\033[0m"
#ssh freebsd "portmaster -BCDa --no-confirm"

echo -e "\033[1;32mUpdating system sources...\n\033[0m"
#ssh freebsd "svn update /usr/src"

echo -e "\033[1;31m"
if ask "Do you want to rebuild world?"; then
  echo -e "\033[1;32mRebuilding world...\n\033[0m"
else
  echo -e "\033[0m"
fi

if ask "Do you want to rebuild the kernel?"; then
  echo -e "\033[1;32mRebuilding kernel...\n\033[0m"
else
  echo -e "\033[0m"
fi


